name: break
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.BREAK_PROJECT_ID }}
on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - "packages/**"
      - "apps/break/**"

jobs:
  deploy:
    uses: ./.github/workflows/common.yml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
