name: break
env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.STORYBOOK_PROJECT_ID }}
on:
  push:
    branches:
      - develop
    paths:
      - "packages/**"

jobs:
  deploy:
    uses: ./.github/workflows/common.yml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
